### ISSUE TITLE
Video stream laggy via WiFi

### ISSUE THREAD

**Issue by m-hofmann** [weiss19ja/amos-ss16-proj2#28]
When accessing the device via WiFi, the video stream is laggy. Probably, the quality is too high for the WiFi's speed.

**Comment by weiss19ja** [comment]
The video stream lag is not a problem which is caused by the uv4l server because after watching the cpu and memory usage the work load staid constant.
After some configuration in the uv4l settings the stream only got a little bit better by setting the sharpness and the jpeg quality down so that the data which were send over the network are getting lower:

commit b1f061f3172e844b100871d3297fc6a409cfe012

**Comment by m-hofmann** [comment]
The video stream is as good as it will get.
